// Generated by CoffeeScript 1.9.1
(function() {
  var findFirstChildInHead, globalReset, resetBody, resetBoxModel, resetFont, resetHtml5, resetTable, resetTableCell;

  findFirstChildInHead = function() {
    return document.head.firstChild;
  };

  resetBoxModel = "margin: 0;\npadding: 0;\nborder: 0;\noutline: 0;";

  resetFont = "font-weight: inherit;\nfont-style: inherit;\nfont-family: inherit;\nfont-size: 100%;\nvertical-align: baseline;";

  resetBody = "line-height: 1;\ncolor: black;\nbackground: white;";

  resetTable = "border-collapse: separate;\nborder-spacing: 0;\nvertical-align: middle;";

  resetTableCell = "text-align: left;\nfont-weight: normal;\nvertical-align: middle;";

  resetHtml5 = "article, aside, canvas, details, figcaption,\nfigure, footer, header, hgroup, menu, nav,\nsection, summary, main {\n" + resetBoxModel + "\ndisplay: block;\n}\naudio, canvas, video {\n    display inline-block;\n    *display inline;\n    *zoom 1;\n}\naudio:not([controls]),[hidden] {\n    display none;\n}";

  globalReset = "html, body, div, span, applet, object, iframe,\nh1, h2, h3, h4, h5, h6, p, blockquote, pre,\na, abbr, acronym, address, big, cite, code,\ndel, dfn, em, img, ins, kbd, q, s, samp,\nsmall, strike, strong, sub, sup, tt, var,\ndl, dt, dd, ol, ul, li,\nfieldset, form, label, legend,\ntable, caption, tbody, tfoot, thead, tr, th, td {\n" + resetBoxModel + "\n" + resetFont + "\n}\nbody {\n" + resetBody + "\n}\ntable {\n" + resetTable + "\n}\ncaption, th, td {\n" + resetTableCell + "\n}\na img {\n    border: none\n}\n" + resetHtml5;

  module.exports = function() {
    var css, firstChild;
    css = document.createElement('style');
    css.type = 'text/css';
    css.innerHTML = globalReset;
    firstChild = findFirstChildInHead();
    if (firstChild != null) {
      document.head.insertBefore(css, firstChild);
    } else {
      document.head.appendChild(css);
    }
    return css;
  };

}).call(this);
